# Steam's videogames platform 👾

> Source: https://app.jedha.co/course/project-steam-ft/steam-ft

![Steam](https://full-stack-assets.s3.eu-west-3.amazonaws.com/images/Steam_2016_logo_black.png)

## Company's description 📇

**Steam** is a [video game digital distribution](https://en.wikipedia.org/wiki/Digital_distribution_of_video_games "Digital distribution of video games") service and storefront from [Valve](https://en.wikipedia.org/wiki/Valve_Corporation "Valve Corporation"). It was launched as a software client in September 2003 to provide game updates automatically for Valve's games, and expanded to distributing third-party titles in late 2005. Steam offers various features, like [digital rights management](https://en.wikipedia.org/wiki/Digital_rights_management "Digital rights management") (DRM), [game server matchmaking](https://en.wikipedia.org/wiki/Matchmaking_\(video_games\) "Matchmaking (video games)") with [Valve Anti-Cheat](https://en.wikipedia.org/wiki/Valve_Anti-Cheat "Valve Anti-Cheat") measures, [social networking](https://en.wikipedia.org/wiki/Social_networking_service "Social networking service"), and [game streaming](https://en.wikipedia.org/wiki/Video_game_live_streaming "Video game live streaming") services. Steam client's functions include game update automation, cloud storage for [game progress](https://en.wikipedia.org/wiki/Saved_game "Saved game"), and community features such as direct messaging, in-game overlay functions and a virtual [collectable](https://en.wikipedia.org/wiki/Collectable "Collectable") marketplace.

## Project 🚧

You're working for [Ubisoft](www.ubisoft.com), a French video game publisher. They'd like to release a new revolutionary videogame! They asked you conduct a global analysis of the games available on Steam's marketplace in order to better understand the videogames ecosystem and today's trends.

## Goals 🎯

The ultimate goal of this project is to understand what factors affect the popularity or sales of a video game. But your boss asked you to take advantage of this opportunity to analyze the video game market globally.

To carry out this project, you will have to adopt different levels of analysis. Your boss gave you a list of examples of questions that would be interesting:

**Analysis at the "macro" level**

-   Which publisher has released the most games on Steam?
    
-   What are the best rated games?
    
-   Are there years with more releases? Were there more or fewer game releases during the Covid, for example?
    
-   How are the prizes distributed? Are there many games with a discount?
    
-   What are the most represented languages?
    
-   Are there many games prohibited for children under 16/18?
    

**Genres analysis**

-   What are the most represented genres?
    
-   Are there any genres that have a better positive/negative review ratio?
    
-   Do some publishers have favorite genres?
    
-   What are the most lucrative genres?
    

**Platform analysis**

-   Are most games available on Windows/Mac/Linux instead?
    
-   Do certain genres tend to be preferentially available on certain platforms?
    

You're free to follow these guidelines, or to choose a different angle of analysis, as long as your analysis reveals relevant and useful information. 🤓

## Scope of this project 🖼️

You'll have to use **Databricks** and **PySpark** to conduct this EDA. Particularly, you'll have to use [Databrick's visualisation tool](https://docs.databricks.com/visualizations/index.html) to create the visualizations.

The dataset is available in our S3 bucket at the following url: `s3://full-stack-bigdata-datasets/Big_Data/Project_Steam/steam_game_output.json`.

## Helpers 🦮

To help you achieve this project, here are a few tips that should help you:

-   To adopt different levels of analysis, it might be useful to create different dataframes.
    
-   As the dataset is semi-structured with a **nested schema**, Pyspark's methods such as `getField()` and `explode()` may help you.
    
-   There are some text and date fields in this dataset: Pyspark offers utilitary functions to manipulate these types of data efficiently 💡
    
-   You can use agregate functions and `groupBy` to conduct segmented analysis.
    

## Deliverable 📬

To complete this project, you should deliver:

-   One or several notebooks including data manipulation with PySpark and data visualization with Databrick's dashboarding tool.
    
-   To make sure the jury can view all the visualizations, please use the "publish" button on Databricks notebooks to create a public url where a copy of your notebook will be available.
    
-   While using the "publish" button, Databricks may tell you that your notebook's size exceeds the maximal size allowed. If this happens, just split your notebook in several notebooks.
    
-   Please copy-paste the link(s) to your published notebooks into your Github repo such that the jury can access it easily. 😌
    

![](https://full-stack-assets.s3.eu-west-3.amazonaws.com/images/databricks_publish.png)

In [0]:
# import libraries

from pyspark.sql import SparkSession, functions as F

from pyspark.sql.functions import (
    explode, desc,  row_number, col, try_divide, year, try_to_date, count, 
    countDistinct
)

from pyspark.sql.window import Window

# import pandas as pd


In [0]:
# curl https://full-stack-bigdata-datasets.s3.amazonaws.com/Big_Data/Project_Steam/steam_game_output.json
# record a file in local wget -O steam_game_output.json https://full-stack-bigdata-datasets.s3.amazonaws.com/Big_Data/Project_Steam/steam_game_output.json

In [0]:
# from pyspark.sql import SparkSession

filepath = "s3://full-stack-bigdata-datasets/Big_Data/Project_Steam/steam_game_output.json"

df = spark.read.format('json').load(filepath)

In [0]:
# Number of elements in dataframe
print(f"Entries number : {df.count()}")


Entries number : 55691


The dataset is to big for json_normalize method.

In [0]:
type(df)

pyspark.sql.connect.dataframe.DataFrame

In [0]:
df.take(1)

[Row(data=Row(appid=10, categories=['Multi-player', 'Valve Anti-Cheat enabled', 'Online PvP', 'Shared/Split Screen PvP', 'PvP'], ccu=13990, developer='Valve', discount='0', genre='Action', header_image='https://cdn.akamai.steamstatic.com/steam/apps/10/header.jpg?t=1666823513', initialprice='999', languages='English, French, German, Italian, Spanish - Spain, Simplified Chinese, Traditional Chinese, Korean', name='Counter-Strike', negative=5199, owners='10,000,000 .. 20,000,000', platforms=Row(linux=True, mac=True, windows=True), positive=201215, price='999', publisher='Valve', release_date='2000/11/1', required_age='0', short_description="Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team's success. Your team's success affects your role.", tags=Row(1980s=266, 1990's=1191, 2.5

In [0]:
df.printSchema()

root
 |-- data: struct (nullable = true)
 |    |-- appid: long (nullable = true)
 |    |-- categories: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- ccu: long (nullable = true)
 |    |-- developer: string (nullable = true)
 |    |-- discount: string (nullable = true)
 |    |-- genre: string (nullable = true)
 |    |-- header_image: string (nullable = true)
 |    |-- initialprice: string (nullable = true)
 |    |-- languages: string (nullable = true)
 |    |-- name: string (nullable = true)
 |    |-- negative: long (nullable = true)
 |    |-- owners: string (nullable = true)
 |    |-- platforms: struct (nullable = true)
 |    |    |-- linux: boolean (nullable = true)
 |    |    |-- mac: boolean (nullable = true)
 |    |    |-- windows: boolean (nullable = true)
 |    |-- positive: long (nullable = true)
 |    |-- price: string (nullable = true)
 |    |-- publisher: string (nullable = true)
 |    |-- release_date: string (nullable = true)
 |    |-

We observe 23 different values : data is a only a node, categories, platforms and tags contain nested informations. Let's flatened the dataframe to range datas at same level. 

In [0]:
from pyspark.sql.functions import concat_ws

flat_df = df.select("id","data.*", concat_ws(", ", "data.categories").alias("category"))
flat_df.limit(1).display()

id,appid,categories,ccu,developer,discount,genre,header_image,initialprice,languages,name,negative,owners,platforms,positive,price,publisher,release_date,required_age,short_description,tags,type,website,category
10,10,"List(Multi-player, Valve Anti-Cheat enabled, Online PvP, Shared/Split Screen PvP, PvP)",13990,Valve,0,Action,https://cdn.akamai.steamstatic.com/steam/apps/10/header.jpg?t=1666823513,999,"English, French, German, Italian, Spanish - Spain, Simplified Chinese, Traditional Chinese, Korean",Counter-Strike,5199,"10,000,000 .. 20,000,000","List(true, true, true)",201215,999,Valve,2000/11/1,0,Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team's success. Your team's success affects your role.,"List(266, 1191, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5426, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 227, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2784, null, null, null, null, null, null, null, null, null, null, null, null, 1607, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 4831, null, null, null, null, null, null, null, null, null, 1707, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 632, null, null, null, null, null, null, null, null, null, null, null, 3392, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 131, null, null, 769, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 881, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 289, null, null, null, 3353, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 614, null, null, null, null, null, null, 304, null, null, null, 1344, null, null, 1864, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1192)",game,,"Multi-player, Valve Anti-Cheat enabled, Online PvP, Shared/Split Screen PvP, PvP"


In [0]:
# from pyspark.sql import functions as F

flat_df = flat_df.withColumn(
    "platform",
    F.concat_ws(', ', *[F.when(F.col(f"platforms.{f}"), F.lit(f)) for f in ['linux', 'mac', 'windows']])
)
flat_df.limit(1).display()

id,appid,categories,ccu,developer,discount,genre,header_image,initialprice,languages,name,negative,owners,platforms,positive,price,publisher,release_date,required_age,short_description,tags,type,website,category,platform
10,10,"List(Multi-player, Valve Anti-Cheat enabled, Online PvP, Shared/Split Screen PvP, PvP)",13990,Valve,0,Action,https://cdn.akamai.steamstatic.com/steam/apps/10/header.jpg?t=1666823513,999,"English, French, German, Italian, Spanish - Spain, Simplified Chinese, Traditional Chinese, Korean",Counter-Strike,5199,"10,000,000 .. 20,000,000","List(true, true, true)",201215,999,Valve,2000/11/1,0,Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team's success. Your team's success affects your role.,"List(266, 1191, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5426, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 227, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2784, null, null, null, null, null, null, null, null, null, null, null, null, 1607, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 4831, null, null, null, null, null, null, null, null, null, 1707, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 632, null, null, null, null, null, null, null, null, null, null, null, 3392, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 131, null, null, 769, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 881, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 289, null, null, null, 3353, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 614, null, null, null, null, null, null, 304, null, null, null, 1344, null, null, 1864, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1192)",game,,"Multi-player, Valve Anti-Cheat enabled, Online PvP, Shared/Split Screen PvP, PvP","linux, mac, windows"


In [0]:
flat_df = flat_df.withColumn("tag", F.to_json(F.col("tags")))
flat_df.limit(1).display()

id,appid,categories,ccu,developer,discount,genre,header_image,initialprice,languages,name,negative,owners,platforms,positive,price,publisher,release_date,required_age,short_description,tags,type,website,category,platform,tag
10,10,"List(Multi-player, Valve Anti-Cheat enabled, Online PvP, Shared/Split Screen PvP, PvP)",13990,Valve,0,Action,https://cdn.akamai.steamstatic.com/steam/apps/10/header.jpg?t=1666823513,999,"English, French, German, Italian, Spanish - Spain, Simplified Chinese, Traditional Chinese, Korean",Counter-Strike,5199,"10,000,000 .. 20,000,000","List(true, true, true)",201215,999,Valve,2000/11/1,0,Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team's success. Your team's success affects your role.,"List(266, 1191, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5426, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 227, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2784, null, null, null, null, null, null, null, null, null, null, null, null, 1607, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 4831, null, null, null, null, null, null, null, null, null, 1707, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 632, null, null, null, null, null, null, null, null, null, null, null, 3392, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 131, null, null, 769, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 881, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 289, null, null, null, 3353, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 614, null, null, null, null, null, null, 304, null, null, null, 1344, null, null, 1864, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1192)",game,,"Multi-player, Valve Anti-Cheat enabled, Online PvP, Shared/Split Screen PvP, PvP","linux, mac, windows","{""1980s"":266,""1990's"":1191,""Action"":5426,""Assassin"":227,""Classic"":2784,""Competitive"":1607,""FPS"":4831,""First-Person"":1707,""Military"":632,""Multiplayer"":3392,""Nostalgia"":131,""Old School"":769,""PvP"":881,""Score Attack"":289,""Shooter"":3353,""Strategy"":614,""Survival"":304,""Tactical""

In [0]:
flat_df = flat_df.drop( "categories", "platforms", "tags")
flat_df.printSchema()

root
 |-- id: string (nullable = true)
 |-- appid: long (nullable = true)
 |-- ccu: long (nullable = true)
 |-- developer: string (nullable = true)
 |-- discount: string (nullable = true)
 |-- genre: string (nullable = true)
 |-- header_image: string (nullable = true)
 |-- initialprice: string (nullable = true)
 |-- languages: string (nullable = true)
 |-- name: string (nullable = true)
 |-- negative: long (nullable = true)
 |-- owners: string (nullable = true)
 |-- positive: long (nullable = true)
 |-- price: string (nullable = true)
 |-- publisher: string (nullable = true)
 |-- release_date: string (nullable = true)
 |-- required_age: string (nullable = true)
 |-- short_description: string (nullable = true)
 |-- type: string (nullable = true)
 |-- website: string (nullable = true)
 |-- category: string (nullable = false)
 |-- platform: string (nullable = false)
 |-- tag: string (nullable = true)



In [0]:
# flat_df.write.csv("df.csv", header=True)

Export a csv with the .write method requires missing write right on working directory in databricks free edition. So, let's use pandas method .tocsv()

In [0]:
# import pandas as pd

# flat_df.toPandas().to_csv("df.csv", index=False)

# Explorary dataset analysis

## 1. Explore dataset

In [0]:
len(flat_df.columns)

23

In [0]:
flat_df.count()

55691

The dataframe has 23 columns and 55691 rows.

Now, let's query on the dataframe. Spark lets us run classic SQL queries on your tables, however, using classic SQL in Spark requires you to load the data in memory before running any query. We will use the .createOrReplaceTempView Spark DataFrame method in order to load the data in memory under a certain table name, we will then be able to run SQL queries on it.

In [0]:
flat_df.createOrReplaceTempView('temp_table') # Creates a temporary view table in memory called temp_table
result = spark.sql("select * from temp_table limit 1")
result.show()

+---+-----+-----+---------+--------+------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+
| id|appid|  ccu|developer|discount| genre|        header_image|initialprice|           languages|          name|negative|              owners|positive|price|publisher|release_date|required_age|   short_description|type|website|            category|           platform|                 tag|
+---+-----+-----+---------+--------+------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+
| 10|   10|13990|    Valve|       0|Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,00

The .sql method lets you write queries in SQL while benefiting from the distributed computing advantages of Spark.

In [0]:
result = spark.sql("SELECT * FROM temp_table LIMIT 1") # filters elements from temp_table 
# show everything
result.show()

+---+-----+-----+---------+--------+------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+
| id|appid|  ccu|developer|discount| genre|        header_image|initialprice|           languages|          name|negative|              owners|positive|price|publisher|release_date|required_age|   short_description|type|website|            category|           platform|                 tag|
+---+-----+-----+---------+--------+------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+
| 10|   10|13990|    Valve|       0|Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,00

We observe 
- ccu nombre de joueurs qui jouaient simulatanément au moment où le dataset a été construit
- discount en pourcentage
- prix stocké en centimes de dollars
- owners indique un intervalle pour évaluer le nombre d'acheteurs
- categories la liste varie selon le jeu. Elles permettent aux acheteurs de classer les jeux et fonctionnent comme les étagères d'une bibliothèque.
- duplicated rows ?

some problems :
- unused spaces : sort columns to verify wether it's a display problem or requests problem 
- different spelling : lowercase string columns
- special alphabetic characters on string columns developers '---', "flyingcubicle, - ", "((no-end-parens studio", "revday studio", "+7 software" , "+mpact games, llc."  
- empty entries : '' on website and platform -> verify other columns
- unused columns : id and appid are identifyers, we use name and can delete them, website, header_image 
- des colonnes numériques au format string -> convertir price, initialprice, discount, required_age au format long
- release_date string for datetime

We must verify with steam team before treat these data.
- special alphabetic characters : "," is a separator that we can use to count entries on developers, genre, languages. 
Are " ", None, ., CD PROJEKT RED, [2.21] real publishers and '---', "flyingcubicle, - ", "((no-end-parens studio", "revday studio", "+7 software" , "+mpact games, llc." real developers ?
Are "(none)", " ", "-" real publishers ?
- asiatic characters. We need information even if the langage changes.

Let's sample and observe values on selected columns.

In [0]:
flat_df.select('developer', 'publisher', 'owners', 'ccu', 'website', 'header_image').sample(fraction=0.0001).distinct().show(truncate=False)

+--------------------------------------+-------------------------------+--------------------+---+---------------------------------------------------------------------------------+-----------------------------------------------------------------------------+
|developer                             |publisher                      |owners              |ccu|website                                                                          |header_image                                                                 |
+--------------------------------------+-------------------------------+--------------------+---+---------------------------------------------------------------------------------+-----------------------------------------------------------------------------+
|PestoForce                            |Armor Games Studios, PestoForce|20,000 .. 50,000    |0  |http://www.SuperChibiKnight.com                                                  |https://cdn.akamai.steamstatic.com/steam/apps/2

In [0]:
spark.sql("select * from temp_table limit 5").show()

+-------+-------+-----+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------------+--------+--------------------+--------+-----+--------------------+------------+------------+-------------------------------------+----+--------------------+--------------------+-------------------+--------------------+
|     id|  appid|  ccu|           developer|discount|               genre|        header_image|initialprice|           languages|                name|negative|              owners|positive|price|           publisher|release_date|required_age|                    short_description|type|             website|            category|           platform|                 tag|
+-------+-------+-----+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------------+--------+--------------------+--------+-----+--------------------+------------+------------+--------------------

In [0]:
result = spark.sql("select distinct type from temp_table")
result.show()

+--------+
|    type|
+--------+
|hardware|
|    game|
+--------+



In [0]:
result = spark.sql("select * from temp_table where type = 'hardware'")
result.show(truncate=False)

+------+------+---+---------+--------+-----+----------------------------------------------------------------------------+------------+---------+----------+--------+--------------------+--------+-----+-----------+------------+------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+-----------------------------------------+---------------------------------------------+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|id    |appid |ccu|developer|discount|genre|header_image                                                                |initialprice|languages|name      

Steam link est un outil édité par Anima Locus qui permet d'accéder à un jeu par lien sur le téléphone, une tablette, un autre PC et même d'accéder à un jeu hébergé sur le pc d'un ami. Ce n'est pas un jeu en soi. Il convient de supprimer la colonne type.

In [0]:
result = spark.sql("select distinct name from temp_table where name like'Counter-Strike%'")
result.show(truncate=False)

+--------------------------------+
|name                            |
+--------------------------------+
|Counter-Strike Nexon: Studio    |
|Counter-Strike: Global Offensive|
|Counter-Strike: Source          |
|Counter-Strike: Condition Zero  |
|Counter-Strike                  |
+--------------------------------+



Une entrée ne correspond pas forcément à un nom de jeu. Ici, les informations diffèrent totalement pour le même jeu.

In [0]:
result = spark.sql("select count (distinct name) as games_nb from temp_table")
result.show(truncate=False)

+--------+
|games_nb|
+--------+
|55430   |
+--------+



En réalité, le fichier référence 55430 nom de jeux. 

In [0]:
result = spark.sql("select * from temp_table where name like'Alone'")
result.show(truncate=False)

+-------+-------+---+--------------------+--------+-------------------------------------------+-----------------------------------------------------------------------------+------------+---------+-----+--------+-----------+--------+-----+--------------------+------------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+-------+-------------------------------------------------------------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|id     |appid  |ccu|developer           |discount|genre       

Mais en détail le jeu Alone qui est référencé 5 fois contient des données description, developer, publisher, genre, price, initialprice, positive, negative, release_date, category, tag totalement différentes. Je ne peux pas garantir que ces jeux soient identiques. Il manque les informations concernant la marque, les brevets éventuels, voire les registres.

In [0]:
result = spark.sql("select count(appid) as appid_nb, name from temp_table group by name order by appid_nb desc limit 5")
result.show(truncate=False)

+--------+------+
|appid_nb|name  |
+--------+------+
|5       |Alone |
|4       |Bounce|
|4       |Escape|
|4       |Dodge |
|4       |Lost  |
+--------+------+



In [0]:
result = spark.sql("select count(appid) as appid_nb from temp_table where appid != id ")
result.show(truncate=False)

+--------+
|appid_nb|
+--------+
|0       |
+--------+



appid et id ont des valeurs identiques mais le format diffère. 
Arbitrage : conserver appid car il est au format long, adapté pour stocker des valeurs numériques.

In [0]:
from pyspark.sql.functions import col

string_cols = [field.name for field in flat_df.schema.fields if field.dataType.simpleString() == 'string']

for c in string_cols:
    count = flat_df.filter(col(c) == '').count()
    if count > 0:
        print(f"{c}: {count}")

developer: 127
genre: 161
languages: 11
publisher: 132
release_date: 99
short_description: 37
website: 25217
category: 970


In [0]:
result = spark.sql("select * from temp_table where release_date = ''")
result.show()

+-------+-------+---+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------------+--------+--------------------+--------+-----+--------------------+------------+------------+--------------------+----+--------------------+--------------------+-------------------+--------------------+
|     id|  appid|ccu|           developer|discount|               genre|        header_image|initialprice|           languages|                name|negative|              owners|positive|price|           publisher|release_date|required_age|   short_description|type|             website|            category|           platform|                 tag|
+-------+-------+---+--------------------+--------+--------------------+--------------------+------------+--------------------+--------------------+--------+--------------------+--------+-----+--------------------+------------+------------+--------------------+----+--------------------+-------------

In [0]:
from pyspark.sql.functions import col, sum as spark_sum

all_cols = flat_df.columns
string_cols = [f.name for f in flat_df.schema.fields if f.dataType.simpleString() == 'string']

flat_df.select([spark_sum((col(c).isNull() | ((col(c) == '') if c in string_cols else False)).cast('int')).alias(c) for c in all_cols]).show()

+---+-----+---+---------+--------+-----+------------+------------+---------+----+--------+------+--------+-----+---------+------------+------------+-----------------+----+-------+--------+--------+---+
| id|appid|ccu|developer|discount|genre|header_image|initialprice|languages|name|negative|owners|positive|price|publisher|release_date|required_age|short_description|type|website|category|platform|tag|
+---+-----+---+---------+--------+-----+------------+------------+---------+----+--------+------+--------+-----+---------+------------+------------+-----------------+----+-------+--------+--------+---+
|  0|    0|  0|      127|       0|  161|           0|           0|       11|   0|       0|     0|       0|    0|      132|          99|           0|               37|   0|  25217|     970|       0|  0|
+---+-----+---+---------+--------+-----+------------+------------+---------+----+--------+------+--------+-----+---------+------------+------------+-----------------+----+-------+--------+----

In pyspark, missing values on strings are empty values. There are 55691 rows. Website misses on one half rows. Other missing values should be converted.


In [0]:
flat_df.count() == flat_df.dropDuplicates().count()

True

There are no duplicated rows.

In [0]:
(flat_df.count() - flat_df.dropDuplicates().count())

0

## 2. Clean data

Let's record clean_data under a new dataframe and create a new temp view.

In [0]:
clean_df = flat_df
clean_df.createOrReplaceTempView('table')

In [0]:
result = clean_df \
    .filter(clean_df.name == 'Alone')
result.show(truncate=False)

+-------+-------+---+--------------------+--------+-------------------------------------------+-----------------------------------------------------------------------------+------------+---------+-----+--------+-----------+--------+-----+--------------------+------------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+-------+-------------------------------------------------------------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|id     |appid  |ccu|developer           |discount|genre       

### a) treatments
Let's clean data. 
#### trim
First, delete unused spaces with trim method.

In [0]:
from pyspark.sql.functions import trim

clean_df = clean_df \
    .select([trim(col(c)).alias(c) for c in clean_df.columns])
clean_df.show(1)


+---+-----+-----+---------+--------+------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+
| id|appid|  ccu|developer|discount| genre|        header_image|initialprice|           languages|          name|negative|              owners|positive|price|publisher|release_date|required_age|   short_description|type|website|            category|           platform|                 tag|
+---+-----+-----+---------+--------+------+--------------------+------------+--------------------+--------------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+-------+--------------------+-------------------+--------------------+
| 10|   10|13990|    Valve|       0|Action|https://cdn.akama...|         999|English, French, ...|Counter-Strike|    5199|10,00

#### Normalization 
Any values are string. We must standardize before converting.

##### price

In [0]:
from pyspark.sql import functions as F

price_cols = ['price', 'initialprice']
clean_df = clean_df.withColumns({p: F.col(p) / 100 for p in price_cols})
clean_df.select('price', 'initialprice').show(5)

+-----+------------+
|price|initialprice|
+-----+------------+
| 9.99|        9.99|
| 9.99|        9.99|
| 5.99|       19.99|
|19.99|       19.99|
| 1.99|        1.99|
+-----+------------+
only showing top 5 rows


##### required_age

In [0]:
from pyspark.sql import functions as F
from pyspark.sql.functions import col, desc
result = clean_df \
    .select('appid', 'required_age') \
    .dropDuplicates(['appid']) \
    .groupBy('required_age') \
    .agg(F.count('required_age').alias('game_nb')) \
    .orderBy(desc('game_nb'))
result.show()

+------------+-------+
|required_age|game_nb|
+------------+-------+
|           0|  55030|
|          15|    264|
|          18|    223|
|          16|     38|
|          17|     38|
|          12|     32|
|          13|     26|
|          14|     10|
|          10|      7|
|         180|      4|
|           6|      4|
|           8|      3|
|           3|      3|
|           7|      2|
|         21+|      1|
|          7+|      1|
|          20|      1|
|           5|      1|
|           9|      1|
|          35|      1|
+------------+-------+
only showing top 20 rows


We observe some strange values. Dans le monde, les interdictions de jeu sur les mineurs s'appliquent jusqu'à 18 ans https://fr.wikipedia.org/wiki/Syst%C3%A8me_d%27%C3%A9valuation_des_jeux_vid%C3%A9o sauf en arabie saoudite, corée à 21 ans.En australie, MA15+ à partir de 15 ans. Globalement, la règle est une constante pour les restrictions avec le symbole +.
Arbitrages : 
- strings supprimés
- 180 et 35 ramenés à 18 ans

In [0]:
rules = [(r'\+|MA |180|35')]
rule = "|".join(rules)
result = clean_df \
    .filter(col("required_age").cast('string').rlike(rule)) \
    .select('required_age') \
    .distinct() \
    .orderBy('required_age')

display(result)

required_age
180
21+
35
7+
MA 15+


In [0]:
from pyspark.sql.functions import regexp_replace, col

rules = [(r'\+|MA ', ''), 
    (r'35|180', '18')]

for search, replace in rules:
    clean_df = clean_df.withColumn("required_age", regexp_replace(col("required_age"), search, replace))
clean_df.show()

+-------+-------+-----+----------------------------+--------+--------------------+--------------------+------------+--------------------+------------------------------------+--------+--------------------+--------+-----+----------------------------+------------+------------+-------------------------------------+----+--------------------+--------------------+-------------------+--------------------+
|     id|  appid|  ccu|                   developer|discount|               genre|        header_image|initialprice|           languages|                                name|negative|              owners|positive|price|                   publisher|release_date|required_age|                    short_description|type|             website|            category|           platform|                 tag|
+-------+-------+-----+----------------------------+--------+--------------------+--------------------+------------+--------------------+------------------------------------+--------+---------------

In [0]:
rules = [(r'\+|MA |180|35')]
rule = "|".join(rules)
result = clean_df \
    .filter(col("required_age").cast('string').rlike(rule)) \
    .select('required_age') \
    .distinct() \
    .orderBy('required_age')

result.show()

+------------+
|required_age|
+------------+
+------------+



##### positive / negative / ccu

positive, negative et ccu sont des chiffres. Ils seront convertis.

##### owners

In [0]:
result = (clean_df \
    .select('appid','owners') \
    .distinct() \
    .groupBy('owners')
    .agg(F.count('owners').alias('game_nb')) \
    .orderBy(desc('game_nb')))
result.show()

+--------------------+-------+
|              owners|game_nb|
+--------------------+-------+
|         0 .. 20,000|  38072|
|    20,000 .. 50,000|   7285|
|   50,000 .. 100,000|   3695|
|  100,000 .. 200,000|   2519|
|  200,000 .. 500,000|   2162|
|500,000 .. 1,000,000|    933|
|1,000,000 .. 2,00...|    526|
|2,000,000 .. 5,00...|    335|
|5,000,000 .. 10,0...|     97|
|10,000,000 .. 20,...|     41|
|20,000,000 .. 50,...|     21|
|50,000,000 .. 100...|      4|
|200,000,000 .. 50...|      1|
+--------------------+-------+



In [0]:
from pyspark.sql.functions import col, split, regexp_replace, desc
clean_df = (clean_df
    .withColumn('extracted_owners', regexp_replace(split(col('owners'), ' ')[2], ',', '')) # keep only high owners number
    .orderBy(desc('extracted_owners')))
clean_df.show(1)

+---+-----+------+---------+--------+--------------------+--------------------+------------+--------------------+------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+--------------------+--------------------+-------------------+--------------------+----------------+
| id|appid|   ccu|developer|discount|               genre|        header_image|initialprice|           languages|  name|negative|              owners|positive|price|publisher|release_date|required_age|   short_description|type|             website|            category|           platform|                 tag|extracted_owners|
+---+-----+------+---------+--------+--------------------+--------------------+------------+--------------------+------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+--------------------+--------------------+-------------------+--------------------+----------------+
|570|  570|85299

In [0]:
result = clean_df \
    .select('appid','extracted_owners') \
    .distinct() \
    .groupBy('extracted_owners') \
    .agg(F.count('extracted_owners').alias('game_nb')) \
    .orderBy(desc('game_nb'))
result.show()

+----------------+-------+
|extracted_owners|game_nb|
+----------------+-------+
|           20000|  38072|
|           50000|   7285|
|          100000|   3695|
|          200000|   2519|
|          500000|   2162|
|         1000000|    933|
|         2000000|    526|
|         5000000|    335|
|        10000000|     97|
|        20000000|     41|
|        50000000|     21|
|       100000000|      4|
|       500000000|      1|
+----------------+-------+



##### date
Then, convert release_date from string to datetime to_date() ne passe pas en raison de valeurs non conformes. Comptez le nombre de segments (/) pour chaque valeur distincte de 'release_date', afin de voir toutes les structures présentes (3 segments, 2 segments, etc.).

In [0]:
from pyspark.sql.functions import col, split, size

clean_df.select('release_date', size(split(col('release_date'), '/')).alias('partition_nb')) \
    .distinct() \
    .groupBy('partition_nb') \
    .count() \
    .show()

+------------+-----+
|partition_nb|count|
+------------+-----+
|           3| 3937|
|           2|   73|
|           1|    1|
+------------+-----+



Résultat clair: Trois structures existent dans 'release_date':

3 segments (3937 lignes): format complet 'yyyy/M/d'
2 segments (73 lignes): année/mois seulement, ex '2019/01'
1 segment (1 ligne): probablement juste l'année

In [0]:
from pyspark.sql.functions import to_date, col, when, split, size, concat, lit

nb_segments = size(split(col('release_date'), '/'))

clean_df = clean_df.withColumn(
    'release_date',
    when(col('release_date') == '', None)
    .when(nb_segments == 3, to_date(col('release_date'), 'yyyy/M/d'))
    .when(nb_segments == 2, to_date(concat(col('release_date'), lit('/1')), 'yyyy/M/d'))
    .when(nb_segments == 1, to_date(concat(col('release_date'), lit('/1/1')), 'yyyy/M/d'))
    .otherwise(None)
)
clean_df.select('release_date').show(1)

+------------+
|release_date|
+------------+
|  2013-07-09|
+------------+
only showing top 1 row


#### convert values
Then, convert numerical columns positive, negative, ccu, price, initialprice, discount, required_age from string to int.

In [0]:
from pyspark.sql.functions import col

int_cols = ['positive', 'negative', 'ccu', 'extracted_owners']
short_cols = ['discount', 'required_age']
decimal_cols = ['price', 'initialprice']


types = {**{c: 'int' for c in int_cols}, **{c: 'short' for c in short_cols}, **{c: 'decimal(5,2)' for c in decimal_cols}}
clean_df = clean_df.withColumns({c: col(c).cast(t) for c, t in types.items()})
clean_df.show(1)

+---+-----+------+---------+--------+--------------------+--------------------+------------+--------------------+------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+--------------------+--------------------+-------------------+--------------------+----------------+
| id|appid|   ccu|developer|discount|               genre|        header_image|initialprice|           languages|  name|negative|              owners|positive|price|publisher|release_date|required_age|   short_description|type|             website|            category|           platform|                 tag|extracted_owners|
+---+-----+------+---------+--------+--------------------+--------------------+------------+--------------------+------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+--------------------+--------------------+-------------------+--------------------+----------------+
|570|  570|85299

#### languages

In [0]:
rules = [
    r'#lang_',
    r'all with full audio support',
    r'full audio',
    r'not supported',
    r'text only',
    r'traditional',
    r'simplified',
    r'\- brazil',
    r'\- portugal',
    r'\(gurmukhi\)',
    r'\- latin america',
    r'\- spain',
    r'english dutch  english',
    r'slovak(?!ian)',
    r';',
    r'\[b\]\*\[/b\]',
    r';',
    r'\[b\]\*\[/b\]',
    r'\r\n'
    r' ,'
    r',(\s*,)+'
    r',\s*'
    r'^,+|,+$'
    ]
rule = "|".join(rules)

result = clean_df \
    .filter(clean_df["languages"].rlike(rule)) \
    .select('languages')

display(result)

languages
"English, French, German, Italian, Spanish - Spain, Portuguese - Portugal, Japanese, Traditional Chinese, Korean, #lang_slovakian, Dutch, Russian, Hungarian, Czech, Polish"
"English, French, German, Spanish - Spain, Italian, Czech, Russian, Hungarian, Polish, Traditional Chinese (text only)"
"English[b]*[/b], German, French, Polish, Spanish - Spain, Italian [b]*[/b]"
"English, French, Spanish - Spain, Italian, German;, Japanese, German"
"English, French, German, Italian, Spanish - Spain, Portuguese - Portugal, Japanese, Traditional Chinese, Korean, #lang_slovakian, Dutch, Russian, Hungarian, Czech, Polish"
"English, French, Spanish - Spain, Italian, German;, Russian, Polish, Japanese, German, Korean"
"English[b]*[/b], German, French, Italian, Spanish - Spain, Russian [b]*[/b]"
"English, French, German, Italian, Spanish - Spain, Japanese, (all with full audio support)"
"English (full audio), French, German, Italian, Spanish - Spain, English"
"English[b]*[/b], French[b]*[/b], Italian[b]*[/b], German[b]*[/b], Spanish - Spain[b]*[/b], Russian, Polish, Korean[b]*[/b], Japanese [b]*[/b]"


Languages regroupe des informations hétérogènes : langues, variantes locales dans certains pays, prise en charge des langues audio. Elle nécessite un nettoyage et une extraction des données par ligne. 

In [0]:
from pyspark.sql.functions import regexp_replace, col, trim

rules = [
    (r'#lang_|\(all with full audio support\)|\(text only\)|\(full audio\)|traditional|simplified|\- brazil|\- portugal|\(gurmukhi\)|\- latin america|\- spain|;|\[b\]\*\[\/b\]|, ', ', '),
    (r'not supported\,', ''),
    (r'english dutch  english', 'english, dutch'),
    (r'slovak(?!ian)', 'slovakian'),
    (r'\r\n', ', '),
    (r' ,', ','),
    (r',(\s*,)+', ','),
    (r',\s*', ', '),
    (r'^,+|,+$', ''),
]

for search, replace in rules:
    clean_df = clean_df.withColumn("languages", trim(regexp_replace(col("languages"), search, replace)))

clean_df.select('languages').show(truncate=False)

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|languages                                                                                                                                                                                                                                                                                                                         |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|English, Bulgarian, Czec

In [0]:
rules = [
    r'#lang_',
    r'all with full audio support',
    r'full audio',
    r'not supported',
    r'text only',
    r'traditional',
    r'simplified',
    r'\- brazil',
    r'\- portugal',
    r'\(gurmukhi\)',
    r'\- latin america',
    r'\- spain',
    r'english dutch  english',
    r'slovak(?!ian)',
    r';',
    r'\[b\]\*\[/b\]',
    r'\r\n'
    r' ,'
    r',(\s*,)+'
    r',\s*'
    r'^,+|,+$'
    ]

rule = "|".join(rules)

result = clean_df \
    .select('languages') \
    .filter(clean_df["languages"].rlike(rule))
result.show(truncate=False)

+---------+
|languages|
+---------+
+---------+



In [0]:
from pyspark.sql.functions import explode, split, trim, col
clean_df = clean_df.withColumn("language", explode(split(trim(col("languages")), ", ")))
clean_df.select('language').show()

+--------------------+
|            language|
+--------------------+
|             English|
|           Bulgarian|
|               Czech|
|              Danish|
|               Dutch|
|             Finnish|
|              French|
|              German|
|               Greek|
|           Hungarian|
|             Italian|
|            Japanese|
|              Korean|
|           Norwegian|
|              Polish|
|Portuguese - Port...|
| Portuguese - Brazil|
|            Romanian|
|             Russian|
|  Simplified Chinese|
+--------------------+
only showing top 20 rows


In [0]:
rules = [
    r'#lang_',
    r'all with full audio support',
    r'full audio',
    r'not supported',
    r'text only',
    r'traditional',
    r'simplified',
    r'\- brazil',
    r'\- portugal',
    r'\(gurmukhi\)',
    r'\- latin america',
    r'\- spain',
    r'english dutch  english',
    r'slovak(?!ian)',
    r';',
    r'\[b\]\*\[/b\]',
    r';',
    r'\[b\]\*\[/b\]',
    r'\r\n'
    r' ,'
    r',(\s*,)+'
    r',\s*'
    r'^,+|,+$'
    ]
rule = "|".join(rules)

result = clean_df \
    .filter(clean_df["language"].rlike(rule)) \
    .select('language')

display(result)

language


In [0]:
result = clean_df \
    .select('appid', 'language') \
    .distinct() \
    .groupBy('language') \
    .agg(count('appid').alias('game_nb')) \
    .orderBy(desc('game_nb'))
result.display()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File <command-5551349593205050>, line 5
      1 result = clean_df \
      2     .select('appid', 'language') \
      3     .distinct() \
      4     .groupBy('language') \
----> 5     .agg(count('appid').alias('game_nb')) \
      6     .orderBy(desc('game_nb'))
      7 result.display()

TypeError: 'int' object is not callable

In [0]:
from pyspark.sql.functions import count

duplicated_entries = clean_df \
    .groupBy('name', "language") \
    .agg(count("language").alias("duplicated_language")) \
    .filter(col('duplicated_language') > 1) \
    .orderBy('duplicated_language', ascending=False)
duplicated_entries.show()

+---------------+--------+-------------------+
|           name|language|duplicated_language|
+---------------+--------+-------------------+
|          Alone| English|                  5|
|          Dodge| English|                  4|
|           Lost| English|                  4|
|         Aurora| English|                  4|
|         Escape| English|                  4|
|         Bounce| English|                  4|
|Northern Lights| English|                  3|
|       Spectrum| English|                  3|
|        Trapped| English|                  3|
|          Chaos| English|                  3|
|          Surge| English|                  3|
|  Hide and Seek| English|                  3|
|        Requiem| English|                  3|
|           Maze| English|                  3|
|      Labyrinth| English|                  3|
|      The Tower| English|                  3|
|      Evolution| English|                  3|
|    Dark Matter| English|                  3|
|          Ar

#### genre

In [0]:
from pyspark.sql.functions import explode, split, trim, col
clean_df = clean_df.withColumn("extracted_genre", explode(split(trim(col("genre")), ", ")))
clean_df.show()

+---+-----+------+---------+--------+--------------------+--------------------+------------+--------------------+------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+--------------------+--------------------+-------------------+--------------------+----------------+---------+---------------+
| id|appid|   ccu|developer|discount|               genre|        header_image|initialprice|           languages|  name|negative|              owners|positive|price|publisher|release_date|required_age|   short_description|type|             website|            category|           platform|                 tag|extracted_owners| language|extracted_genre|
+---+-----+------+---------+--------+--------------------+--------------------+------------+--------------------+------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+--------------------+--------------------+-------------------+---

In [0]:
result = clean_df \
    .select('extracted_genre') \
    .agg(countDistinct('extracted_genre').alias('genre_nb'))
result.show(truncate=False)

+--------+
|genre_nb|
+--------+
|29      |
+--------+



In [0]:
from pyspark.sql.functions import count

duplicated_entries = clean_df \
    .select('appid', 'name', 'extracted_genre') \
    .dropDuplicates(['appid', 'extracted_genre']) \
    .groupBy('name', 'extracted_genre') \
    .agg(count("extracted_genre").alias("duplicated_genre")) \
    .filter(col('duplicated_genre') > 1) \
    .orderBy('duplicated_genre', ascending=False)
duplicated_entries.show(truncate=False)

+---------------+---------------+----------------+
|name           |extracted_genre|duplicated_genre|
+---------------+---------------+----------------+
|Lost           |Indie          |4               |
|Lost           |Adventure      |4               |
|Bounce         |Casual         |4               |
|Escape         |Indie          |4               |
|Alone          |Adventure      |4               |
|Alone          |Indie          |4               |
|Dodge          |Indie          |4               |
|Trapped        |Indie          |3               |
|Northern Lights|Indie          |3               |
|Trapped        |Adventure      |3               |
|Lost           |Casual         |3               |
|Dark Matter    |Action         |3               |
|Hide and Seek  |Indie          |3               |
|Dark Matter    |Indie          |3               |
|Aurora         |Indie          |3               |
|Puzzle Box     |Adventure      |3               |
|Chaos          |Action        

#### tag

In [0]:
result = clean_df \
    .select('appid', 'tag') \
    .distinct() \
    .limit(1)
result.show(truncate=False)

+-----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|appid|tag                                                                                                                                                                                                                                                                                                                                                        |
+-----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [0]:
type(clean_df['tag'])

pyspark.sql.connect.column.Column

Les tags sont couplés à un nombre de votes. Pour les conserver, il est nécessaire de mapper les informations avant de les extraire.

In [0]:
from pyspark.sql.functions import from_json, explode, col
from pyspark.sql.types import MapType, StringType, IntegerType

tag_schema = MapType(StringType(), IntegerType())

clean_df = clean_df \
    .dropDuplicates(['appid']) \
    .withColumn("tag_map", from_json(col("tag"), tag_schema)) \
    .select('*', explode(col("tag_map")).alias("extracted_tag", "tag_vote_nb"))

clean_df.show(truncate=False)

+-----+-----+---+---------+--------+----------------------------------------------------+---------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------+----------------------+--------+-----+---------------+------------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+---------------------+----------------------------------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----

In [0]:
result = clean_df \
    .select('appid', 'extracted_tag') \
    .dropDuplicates(['appid']) \
    .agg(countDistinct('extracted_tag').alias('tag_nb'))
result.show(truncate=False)

+------+
|tag_nb|
+------+
|230   |
+------+



In [0]:
clean_df = clean_df.drop('tag_map')

In [0]:
duplicated_entries = clean_df \
    .select('appid', 'name', 'publisher', 'extracted_tag') \
    .dropDuplicates(['appid']) \
    .groupBy('name', "extracted_tag") \
    .agg(count("extracted_tag").alias('duplicated_tag')) \
    .filter(col('duplicated_tag') > 1) \
    .orderBy(desc('duplicated_tag'))
duplicated_entries.show(truncate=False)

+-----------------+-------------+--------------+
|name             |extracted_tag|duplicated_tag|
+-----------------+-------------+--------------+
|Bounce           |Casual       |3             |
|Puzzle Box       |2D           |3             |
|Survived         |Action       |2             |
|Loop             |3D           |2             |
|Arena            |Action       |2             |
|Jumping Knight   |2D           |2             |
|Hatch            |3D           |2             |
|Parasite         |Action       |2             |
|Escape           |2D           |2             |
|Alone            |3D           |2             |
|Requiem          |3D           |2             |
|Alter Ego        |Adventure    |2             |
|Bunker Down      |2D           |2             |
|Hide and Seek    |Action       |2             |
|Space Survival   |2D           |2             |
|The Line         |3D           |2             |
|Squares          |Casual       |2             |
|Space Wars       |2

At each data extract, duplicated entries are generated. So, we will filter on distinct appid to get precises informations. appid est bien un identifiant unique de jeu. Arbitrage : nous considérons chaque appid comme un jeu différent bien que le nom puisse être identique
#### platform

In [0]:
result = clean_df \
    .select('appid', 'platform') \
    .distinct() \
    .groupby('platform') \
    .agg(count('platform').alias('games_nb')) 
result.show()
    

+-------------------+--------+
|           platform|games_nb|
+-------------------+--------+
|                mac|      11|
|              linux|       3|
|            windows|   41164|
|linux, mac, windows|    6790|
|       mac, windows|    5946|
|     linux, windows|    1641|
|         linux, mac|       1|
+-------------------+--------+



In [0]:
from pyspark.sql.functions import explode, split, trim, col
clean_df = clean_df.withColumn("extracted_platform", explode(split(trim(col("platform")), ", ")))
clean_df.show()

+-----+-----+---+---------+--------+--------------------+--------------------+------------+--------------------+-----+--------+--------------------+--------+-----+---------------+------------+------------+--------------------+----+--------------------+--------------------+--------+--------------------+----------------+--------+---------------+-------------------+-----------+------------------+
|   id|appid|ccu|developer|discount|               genre|        header_image|initialprice|           languages| name|negative|              owners|positive|price|      publisher|release_date|required_age|   short_description|type|             website|            category|platform|                 tag|extracted_owners|language|extracted_genre|      extracted_tag|tag_vote_nb|extracted_platform|
+-----+-----+---+---------+--------+--------------------+--------------------+------------+--------------------+-----+--------+--------------------+--------+-----+---------------+------------+------------+-

In [0]:
from pyspark.sql.functions import count

result = clean_df \
    .select('appid', 'extracted_platform') \
    .distinct() \
    .groupBy('extracted_platform') \
    .agg(count("extracted_platform").alias("games_nb")) \
    .orderBy('games_nb', ascending=False)
result.show(truncate=False)

+------------------+--------+
|extracted_platform|games_nb|
+------------------+--------+
|windows           |55541   |
|mac               |12748   |
|linux             |8435    |
+------------------+--------+



#### missing values
Then, deal with latest missing values.

In [0]:
from pyspark.sql.functions import col, when, to_date, lit

for field in clean_df.schema.fields:
    c = field.name
    if field.dataType.simpleString() == 'string':
        clean_df = clean_df.withColumn(c, when(col(c) == '', 'None').otherwise(col(c)))
    elif c == 'release_date':
        clean_df = clean_df.withColumn(c, when(col(c).isNull(), to_date(lit('1900-01-01'), 'yyyy-MM-dd')).otherwise(col(c)))

clean_df.filter(col('release_date') == to_date(lit('1900-01-01'), 'yyyy-MM-dd')).show(1)

+-----+-----+---+---------+--------+------+--------------------+------------+--------------------+---------------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+--------------------+--------------------+--------+--------------------+----------------+--------+---------------+-------------+-----------+------------------+
|   id|appid|ccu|developer|discount| genre|        header_image|initialprice|           languages|           name|negative|              owners|positive|price|publisher|release_date|required_age|   short_description|type|             website|            category|platform|                 tag|extracted_owners|language|extracted_genre|extracted_tag|tag_vote_nb|extracted_platform|
+-----+-----+---+---------+--------+------+--------------------+------------+--------------------+---------------+--------+--------------------+--------+-----+---------+------------+------------+--------------------+----+-----------------

In [0]:
result = clean_df.filter(col('release_date').isNull()).count()

#### lowercase values
Then, lowercase all values.

In [0]:
from pyspark.sql.functions import lower, col

string_cols = [f.name for f in clean_df.schema.fields if f.dataType.simpleString() == 'string']

clean_df = clean_df.select([lower(col(c)).alias(c) for c in string_cols] + [col(c) for c in clean_df.columns if c not in string_cols])
clean_df.show(1)

+-----+---------+--------------------+--------------------+--------------------+-----+--------------------+---------------+--------------------+----+--------------------+--------------------+--------+--------------------+--------+---------------+-------------+------------------+-----+---+--------+------------+--------+--------+-----+------------+------------+----------------+-----------+
|   id|developer|               genre|        header_image|           languages| name|              owners|      publisher|   short_description|type|             website|            category|platform|                 tag|language|extracted_genre|extracted_tag|extracted_platform|appid|ccu|discount|initialprice|negative|positive|price|release_date|required_age|extracted_owners|tag_vote_nb|
+-----+---------+--------------------+--------------------+--------------------+-----+--------------------+---------------+--------------------+----+--------------------+--------------------+--------+------------------

#### drop columns

Endly, drop unused columns.

In [0]:
clean_df = clean_df.drop('id', 'type', 'header_image', 'website', 'languages', 'genre', 'tag', 'platform')

### b) verify clean_df dataframe

In [0]:
clean_df.createOrReplaceTempView('table') # Refresh the temporary view table in memory
result = spark.sql("select * from table limit 1")
result.show()

+----------------+--------------------+--------------------+----------------+--------------------+--------------------+--------+---------------+-------------+------------------+-------+----+--------+------------+--------+--------+-----+------------+------------+----------------+-----------+
|       developer|                name|              owners|       publisher|   short_description|            category|language|extracted_genre|extracted_tag|extracted_platform|  appid| ccu|discount|initialprice|negative|positive|price|release_date|required_age|extracted_owners|tag_vote_nb|
+----------------+--------------------+--------------------+----------------+--------------------+--------------------+--------+---------------+-------------+------------------+-------+----+--------+------------+--------+--------+-----+------------+------------+----------------+-----------+
|capcom co., ltd.|resident evil vil...|2,000,000 .. 5,00...|capcom co., ltd.|experience surviv...|single-player, st...| engl

In [0]:
clean_df.printSchema()

root
 |-- developer: string (nullable = true)
 |-- name: string (nullable = true)
 |-- owners: string (nullable = true)
 |-- publisher: string (nullable = true)
 |-- short_description: string (nullable = true)
 |-- category: string (nullable = false)
 |-- language: string (nullable = false)
 |-- extracted_genre: string (nullable = false)
 |-- extracted_tag: string (nullable = false)
 |-- extracted_platform: string (nullable = false)
 |-- appid: integer (nullable = true)
 |-- ccu: integer (nullable = true)
 |-- discount: short (nullable = true)
 |-- initialprice: decimal(5,2) (nullable = true)
 |-- negative: integer (nullable = true)
 |-- positive: integer (nullable = true)
 |-- price: decimal(5,2) (nullable = true)
 |-- release_date: date (nullable = true)
 |-- required_age: short (nullable = true)
 |-- extracted_owners: integer (nullable = true)
 |-- tag_vote_nb: integer (nullable = true)



In [0]:
# Number of elements in dataframe
print(f"Entries number : {clean_df.count()}")

Entries number : 946627


In [0]:
result = spark.sql("select * from table limit(5)")
result.show()

+----------------+--------------------+--------------------+----------------+--------------------+--------------------+--------+---------------+-------------+------------------+-------+----+--------+------------+--------+--------+-----+------------+------------+----------------+-----------+
|       developer|                name|              owners|       publisher|   short_description|            category|language|extracted_genre|extracted_tag|extracted_platform|  appid| ccu|discount|initialprice|negative|positive|price|release_date|required_age|extracted_owners|tag_vote_nb|
+----------------+--------------------+--------------------+----------------+--------------------+--------------------+--------+---------------+-------------+------------------+-------+----+--------+------------+--------+--------+-----+------------+------------+----------------+-----------+
|capcom co., ltd.|resident evil vil...|2,000,000 .. 5,00...|capcom co., ltd.|experience surviv...|single-player, st...| engl

In [0]:
clean_df.select('name', 'release_date', 'developer', 'publisher', 'owners', 'ccu').sample(fraction=0.0001).show(truncate=False)

+------------------------------------------------------+------------+----------------------------------------------+-------------------------------------------------------------------+------------------+----+
|name                                                  |release_date|developer                                     |publisher                                                          |owners            |ccu |
+------------------------------------------------------+------------+----------------------------------------------+-------------------------------------------------------------------+------------------+----+
|crosscode                                             |2018-09-20  |radical fish games                            |deck13, whispergames, dangen entertainment, mayflower entertainment|200,000 .. 500,000|224 |
|out of the park baseball 23                           |2022-04-22  |out of the park developments                  |out of the park developments                    

Verify missing values.

In [0]:
from pyspark.sql.functions import col, sum as spark_sum

all_cols = clean_df.columns
string_cols = [f.name for f in clean_df.schema.fields if f.dataType.simpleString() == 'string']

clean_df.select([spark_sum((col(c).isNull() | ((col(c) == '') if c in string_cols else False)).cast('int')).alias(c) for c in all_cols])

clean_df.show()

+----------------+--------------------+--------------------+----------------+--------------------+--------------------+--------+---------------+--------------------+------------------+-------+----+--------+------------+--------+--------+-----+------------+------------+----------------+-----------+
|       developer|                name|              owners|       publisher|   short_description|            category|language|extracted_genre|       extracted_tag|extracted_platform|  appid| ccu|discount|initialprice|negative|positive|price|release_date|required_age|extracted_owners|tag_vote_nb|
+----------------+--------------------+--------------------+----------------+--------------------+--------------------+--------+---------------+--------------------+------------------+-------+----+--------+------------+--------+--------+-----+------------+------------+----------------+-----------+
|capcom co., ltd.|resident evil vil...|2,000,000 .. 5,00...|capcom co., ltd.|experience surviv...|singl

In [0]:
result = spark.sql("select * from table where developer = 'none' or extracted_genre = 'none' or language = 'none' or publisher = 'none' or short_description = 'none' or category = 'none'")
result.limit(1).show()

+--------------+--------------------+----------------+---------+--------------------+--------------------+--------+---------------+-------------+------------------+------+---+--------+------------+--------+--------+-----+------------+------------+----------------+-----------+
|     developer|                name|          owners|publisher|   short_description|            category|language|extracted_genre|extracted_tag|extracted_platform| appid|ccu|discount|initialprice|negative|positive|price|release_date|required_age|extracted_owners|tag_vote_nb|
+--------------+--------------------+----------------+---------+--------------------+--------------------+--------+---------------+-------------+------------------+------+---+--------+------------+--------+--------+-----+------------+------------+----------------+-----------+
|cyanide studio|pro cycling manag...|20,000 .. 50,000|     none|take on the role ...|multi-player, sin...| english|     simulation|    adventure|           windows|25526

In [0]:
result = clean_df \
    .filter(col('release_date') == to_date(lit('1900-01-01'), 'yyyy-MM-dd'))
result.limit(1).show()

+--------------------+--------------------+------------------+----------------+--------------------+--------------------+--------+---------------+-------------+------------------+------+---+--------+------------+--------+--------+-----+------------+------------+----------------+-----------+
|           developer|                name|            owners|       publisher|   short_description|            category|language|extracted_genre|extracted_tag|extracted_platform| appid|ccu|discount|initialprice|negative|positive|price|release_date|required_age|extracted_owners|tag_vote_nb|
+--------------------+--------------------+------------------+----------------+--------------------+--------------------+--------+---------------+-------------+------------------+------+---+--------+------------+--------+--------+-----+------------+------------+----------------+-----------+
|capcom co., ltd.,...|resident evil res...|200,000 .. 500,000|capcom co., ltd.|experience a new ...|multi-player, ste...| en

In [0]:

clean_df.describe().toPandas()

,summary,developer,name,owners,publisher,short_description,category,language,extracted_genre,extracted_tag,extracted_platform,appid,ccu,discount,initialprice,negative,positive,price,required_age,extracted_owners,tag_vote_nb
0,count,946627,946627,946627,946627,946627,946627,946627,946627,946627,946627,946627,946627,946627,946627,946627,946627,946627,946627,946627,946627
1,mean,78791.16374269006,Infinity,None,3063.9032258064517,None,None,None,None,None,None,1061271.778027671,299.3008354927548,3.0932701053318783,8.959132,421.4331294163382,3071.3002016633795,8.630101,0.21642104017738772,345837.3255780788,125.17770146002597
2,stddev,214700.95743280064,NaN,None,1253.4335014359535,None,None,None,None,None,None,551093.7806487436,10381.793501170421,13.886024604155171,10.227744588330038,8440.212493877469,54497.4643205305,10.103348660934188,1.8565876229159668,4564375.971932673,577.6535858134548
3,min,"""nieko""",! that bastard is trying to steal our gold !,"0 .. 20,000","""revday studio""",hungry piggy vs chicken: yes! we are hungry!...,captions available,arabic,accounting,1980s,linux,10,0,0,0.00,0,0,0.00,0,20000,1
4,max,＼上／,～daydream～蝶が舞う頃に,"500,000 .. 1,000,000",ｌｅｍｏｎ ｂａｌｍ,🚗 take part in a roller coaster of emotions wi...,"vr support, steamvr collectibles",turkish,web publishing,zombies,windows,2190950,874053,90,999.00,908515,5943345,999.00,21,500000000,88154


In [0]:
result = clean_df \
    .filter(col('release_date') != to_date(lit('1900-01-01'), 'yyyy-MM-dd')) \
    .select( \
        F.min("release_date").alias("min_release_date"),
        F.max("release_date").alias("max_release_date"))
result.show()

+----------------+----------------+
|min_release_date|max_release_date|
+----------------+----------------+
|      1997-06-30|      2022-11-11|
+----------------+----------------+



## 3. Analysis at the "macro" level
TO DO Nico graph time series

### publisher

#### Which publisher has released the most games on Steam?

In [0]:
from pyspark.sql.functions import count, desc

publisher_leader = clean_df \
    .select(clean_df['publisher'],'appid', 'release_date') \
    .dropDuplicates(['appid']) \
    .groupBy('publisher') \
    .agg(
        count('appid').alias('game_nb'),
        countDistinct('release_date').alias('release_nb')
        ) \
    .orderBy(desc('release_nb'))
publisher_leader.show(1)

+--------------+-------+----------+
|     publisher|game_nb|release_nb|
+--------------+-------+----------+
|big fish games|    423|       404|
+--------------+-------+----------+
only showing top 1 row


#### What is Ubisoft's position as publisher ?

In [0]:
from pyspark.sql.functions import count, desc

publisher_rank = clean_df \
    .select(clean_df['publisher'],'appid', 'release_date') \
    .dropDuplicates(['appid']) \
    .groupBy('publisher') \
    .agg( \
        count('appid').alias('game_nb'), \
        countDistinct('release_date').alias('release_nb')) \
    .withColumn('rank', row_number().over(Window
    .orderBy(desc('release_nb')))) \
    .filter(clean_df.publisher.isin(['big fish games', 'ubisoft','valve']))
publisher_rank.show()

+--------------+-------+----------+----+
|     publisher|game_nb|release_nb|rank|
+--------------+-------+----------+----+
|big fish games|    423|       404|   1|
|       ubisoft|    127|       104|  12|
|         valve|     35|        30| 108|
+--------------+-------+----------+----+



### name

#### How many games on steam ?

In [0]:
games_nb = clean_df \
    .select('appid').distinct() \
    .count()

labels_nb = clean_df \
    .select('name').distinct() \
    .count()
print(f"Games number : {games_nb}\nLabels number = {labels_nb}")

Games number : 55556
Labels number = 55201


Steam references between 55201 and 55556 games. Some games have duplicated nzmes with different characteristics. We can't assert that games with the same name are identical when developped globally at different years. So, we estimate the games number to 55556 games

### developer

#### How many developers referenced on steam ?

In [0]:
developper_nb = clean_df \
    .select(clean_df['developer']) \
    .distinct() \
    .count()
print(f"Developer number : {developper_nb}")



Developer number : 34474


#### Which developer most contribute on steam's games ?

In [0]:
result = clean_df \
    .select(clean_df['developer'],'appid') \
    .distinct() \
    .groupBy('developer') \
    .agg(count('appid').alias('game_nb')) \
    .orderBy(desc('game_nb')) \
    .limit(5)
result.show(truncate=False)

+------------------------+-------+
|developer               |game_nb|
+------------------------+-------+
|choice of games         |140    |
|none                    |131    |
|creobit                 |122    |
|laush dmitriy sergeevich|106    |
|sokpop collective       |98     |
+------------------------+-------+



Choice of games is the more productive developper with 140 games. Choice of games is also a publisher.

### positive / negative / ccu

#### What are the best rated games ?

In [0]:
result = clean_df \
    .select(clean_df['appid'],'name', 'publisher','positive', 'negative') \
    .dropDuplicates(['appid']) \
    .orderBy('positive', ascending=False) \
    .limit(5)
result.show(truncate=False)

+------+--------------------------------+--------------+--------+--------+
|appid |name                            |publisher     |positive|negative|
+------+--------------------------------+--------------+--------+--------+
|730   |counter-strike: global offensive|valve         |5943345 |787093  |
|570   |dota 2                          |valve         |1534895 |317916  |
|271590|grand theft auto v              |rockstar games|1229265 |213379  |
|578080|pubg: battlegrounds             |krafton, inc. |1185361 |908515  |
|105600|terraria                        |re-logic      |1014711 |22380   |
+------+--------------------------------+--------------+--------+--------+



Users evaluate a game by like or dislike.
In 2022, in absolute value, games with the best positive advices number are :
- first counter-strike: global offensive with 5943345 positive advices. 
- 2d, dota 2 with 1534895 positive advices. 
- 3d grand theft auto v with 1229265 positive advices.

In [0]:
from pyspark.sql.functions import col, try_divide

result = clean_df \
    .select(clean_df['appid'],'name', 'publisher','positive', 'negative') \
    .dropDuplicates(['appid']) \
    .groupBy('appid',  'name', 'publisher') \
    .agg( \
        F.sum('positive').alias('positive_sum'), \
        F.sum('negative').alias('negative_sum') \
        ) \
    .filter((col('positive_sum') > 0) & (col('negative_sum') > 0)) \
    .withColumn('ratio', col('positive_sum') /  col('negative_sum')) \
    .orderBy(desc('positive_sum')) \
    .limit(5)
result.show(truncate=False)

+------+--------------------------------+--------------+------------+------------+------------------+
|appid |name                            |publisher     |positive_sum|negative_sum|ratio             |
+------+--------------------------------+--------------+------------+------------+------------------+
|730   |counter-strike: global offensive|valve         |5943345     |787093      |7.551007314256384 |
|570   |dota 2                          |valve         |1534895     |317916      |4.82798915436782  |
|271590|grand theft auto v              |rockstar games|1229265     |213379      |5.760946484893077 |
|578080|pubg: battlegrounds             |krafton, inc. |1185361     |908515      |1.3047236424274777|
|105600|terraria                        |re-logic      |1014711     |22380       |45.34008042895442 |
+------+--------------------------------+--------------+------------+------------+------------------+



In 2022, in relational value, terraria has a better ratio (45.34) than counter-strike: global offensive (7,55) positive advices against 1 negative advice. Yet Terraria is less liked  (1.01M) 1:5. Les jeux avec des avis negatifs sont parfois aussi très appréciés. C'est le cas de pubg: battlegrounds. Counter-strike:global offensive stays the best rated games.

#### Quels sont les jeux les plus utilisés au moment où le dataset a été construit ?

In [0]:
from pyspark.sql.functions import col, try_divide

result = clean_df \
    .select('appid', 'name', 'publisher', 'ccu') \
    .distinct() \
    .orderBy(desc('ccu'))
result.show(truncate=False)

+-------+--------------------------------+-----------------------+------+
|appid  |name                            |publisher              |ccu   |
+-------+--------------------------------+-----------------------+------+
|730    |counter-strike: global offensive|valve                  |874053|
|570    |dota 2                          |valve                  |852995|
|578080 |pubg: battlegrounds             |krafton, inc.          |339287|
|1172470|apex legends                    |electronic arts        |314468|
|1599340|lost ark                        |amazon games           |273088|
|1938090|call of duty: modern warfare ii |activision             |206441|
|271590 |grand theft auto v              |rockstar games         |140671|
|1063730|new world                       |amazon games           |127379|
|252490 |rust                            |facepunch studios      |121146|
|1203220|naraka: bladepoint              |netease games global   |116729|
|431960 |wallpaper engine             

### owners

#### Et quels sont les jeux les plus achetés ?

In [0]:
from pyspark.sql.functions import col, try_divide

result = clean_df \
    .select('appid', 'extracted_owners') \
    .distinct() \
    .groupBy('extracted_owners') \
    .agg( \
        F.count('extracted_owners').alias('game_nb')) \
    .orderBy('game_nb')
result.show(truncate=False)

+----------------+-------+
|extracted_owners|game_nb|
+----------------+-------+
|500000000       |1      |
|100000000       |4      |
|50000000        |21     |
|20000000        |41     |
|10000000        |97     |
|5000000         |335    |
|2000000         |526    |
|1000000         |933    |
|500000          |2162   |
|200000          |2518   |
|100000          |3695   |
|50000           |7285   |
|20000           |37938  |
+----------------+-------+



In [0]:
from pyspark.sql.functions import col, regexp_replace, split, desc

result = clean_df \
    .select('appid', 'name', 'publisher', 'extracted_owners', 'release_date') \
    .distinct() \
    .orderBy(desc('extracted_owners'))
result.show(5, truncate=False)

+-------+--------------------------------+-------------+----------------+------------+
|appid  |name                            |publisher    |extracted_owners|release_date|
+-------+--------------------------------+-------------+----------------+------------+
|570    |dota 2                          |valve        |500000000       |2013-07-09  |
|578080 |pubg: battlegrounds             |krafton, inc.|100000000       |2017-12-21  |
|1063730|new world                       |amazon games |100000000       |2021-09-28  |
|730    |counter-strike: global offensive|valve        |100000000       |2012-08-21  |
|440    |team fortress 2                 |valve        |100000000       |2007-10-10  |
+-------+--------------------------------+-------------+----------------+------------+
only showing top 5 rows


Les jeux les plus plébiscités kingdom rush, crysis et neon chrome ne sont pas forcément les plus utilisés ou les plus achetés :
- dota 2 est le jeu le plus vendu avec 200 000 000 à 500 000 000 utilisateurs. 
- counter-strike: global offensive est plus utilisé avec 874053 utilisateurs mais n'a que 50 000 000 à 100 000 000 d'acheteurs. 
We observe with release_date that dota 2 and conter-strike global offensive are pretty old (2012, 2013).

#### release_date

##### Are there years with more releases ? Were there more or fewer game's releases during the Covid, for example ?

In [0]:
from pyspark.sql.functions import (
    col, year, try_to_date, count, countDistinct
)

result = (clean_df \
    .select('appid', "name", "release_date") \
    .distinct() \
    .withColumn( \
        "release_year", \
        year(try_to_date(col("release_date"), "yyyy/M/d")) \
    ) \
    .filter(col("release_year").isNotNull()) \
    .groupBy("release_year") \
    .agg( \
        count("*").alias("release_nb"), \
        countDistinct("name").alias("name_nb") \
    ) \
    .filter((col('release_nb') > 0) & (col('name_nb') > 0)) \
    .withColumn('ratio', col('release_nb') /  col('name_nb')) \
    .orderBy(desc("release_year")) \
)

result.show()

+------------+----------+-------+------------------+
|release_year|release_nb|name_nb|             ratio|
+------------+----------+-------+------------------+
|        2022|      7454|   7446|1.0010744023636853|
|        2021|      8823|   8809| 1.001589283687138|
|        2020|      8304|   8292|1.0014471780028944|
|        2019|      6940|   6936|1.0005767012687428|
|        2018|      7610|   7598|1.0015793629902605|
|        2017|      5987|   5982| 1.000835840855901|
|        2016|      4182|   4181|1.0002391772303276|
|        2015|      2574|   2573|1.0003886513797124|
|        2014|      1557|   1557|               1.0|
|        2013|       471|    471|               1.0|
|        2012|       345|    345|               1.0|
|        2011|       267|    267|               1.0|
|        2010|       288|    288|               1.0|
|        2009|       309|    309|               1.0|
|        2008|       159|    159|               1.0|
|        2007|        98|     98|             

Yes. There are years with more releases. 
- In absolute value, 2014 to 2022. There are more releases after the covid's year in 2021 with 8676. 
- In prortional value, 2015 to 2022. Releases become higher than games since 2015. Yet, releases are higher on 2020, the covid's year with 1.0011 releases for one game.  
We observe that Covid accentuated the trend which returns then at normal pace in 2022 with 7401 and 1.00094.

### prices

#### How are the prices distributed? 

In [0]:
result = clean_df \
    .select('appid', 'price') \
    .distinct() \
    .groupBy('price') \
    .agg( \
        F.count('price').alias('game_nb')) \
    .orderBy('price')
display(result)

price,game_nb
0.00,7766
0.28,20
0.29,11
0.30,2
0.31,6
0.37,19
0.38,7
0.39,7
0.41,10
0.44,1


Databricks visualization. Run in Databricks to view.

In [0]:
q1, q3 = clean_df.approxQuantile(
    "price",
    [0.25, 0.75],
    0.001
)

iqr = q3 - q1

upper_bound = q3 + 1.5 * iqr

print(f"Q1 : {q1:.2f} $")
print(f"Q3 : {q3:.2f} $")
print(f"IQR : {iqr:.2f} $")
print(f"Upper bound : {upper_bound:.2f} $")

Q1 : 1.99 $
Q3 : 11.99 $
IQR : 10.00 $
Upper bound : 26.99 $


In [0]:
price_df = (
    clean_df
    .select("appid", 'name', "price")
    .distinct()
    .filter(F.col("price").isNotNull())
    .withColumn(
        "price_status",
        F.when(
            F.col("price") > upper_bound,
            "Outlier statistique"
        ).otherwise("Prix courant")
    )
)

In [0]:
median_price = clean_df.approxQuantile(
    "price",
    [0.5],
    0.001
)[0]

print(f"Médiane du prix : {median_price:.2f} $")

Médiane du prix : 5.99 $


In [0]:
display(
    clean_df
    .select("price", 'appid')
    .distinct()
    .filter(F.col("price").isNotNull())
    .withColumn(
    "price_status",
    F.when(
        F.col("price") > upper_bound,
        "Outlier statistique"
    ).otherwise("Prix courant")
))

price,appid,price_status
4.99,945360,Prix courant
0.99,104900,Prix courant
14.99,346010,Prix courant
24.99,1135240,Prix courant
4.99,1393960,Prix courant
0.00,1507970,Prix courant
0.99,1591520,Prix courant
4.99,1615290,Prix courant
0.99,204240,Prix courant
9.99,207650,Prix courant


In [0]:
bin_width = 1 # La granularité à 1 est plus pertinente qu'a 2 pour éviter d'avoir le seuil d'outlier dans une classe. 

In [0]:
# 3. Distribution des jeux par classe de prix
result_bin_1 = (
    clean_df
    .filter(F.col("price").isNotNull())

    # Classe de prix : 0, 2, 4, 6, 8...
    .withColumn(
        "price_bin",
        F.floor(F.col("price") / bin_width) * bin_width
    )


    # Séparation prix courants / outliers
    .withColumn(
        "price_status",
        F.when(
            F.col("price") > upper_bound,
            "Outlier statistique"
        ).otherwise("Prix courant")
    )

    # Comptage des jeux
    .groupBy("price_bin", "price_status", "owners")
    .agg(
        F.count("*").alias("game_nb")
    )

    .orderBy("price_bin")
)

display(result)

price,game_nb
0.00,7766
0.28,20
0.29,11
0.30,2
0.31,6
0.37,19
0.38,7
0.39,7
0.41,10
0.44,1


In [0]:
bin_width = 5 # Nous modifions la granularité des prix après drop des outliers qu'on ne garde pas afin de faire apparaitre les tranches de prix les plus utilisées. 

# 3. Distribution des jeux par classe de prix
result = (
    clean_df
    .filter(F.col("price").isNotNull())
    .drop(F.col("price") > 60)
    # Classe de prix : 0, 2, 4, 6, 8...
    .withColumn(
        "price_bin",
        F.floor(F.col("price") / bin_width) * bin_width
    )


    # Séparation prix courants / outliers
    .withColumn(
        "price_status",
        F.when(
            F.col("price") > upper_bound,
            "Outlier statistique"
        ).otherwise("Prix courant")
    )

    # Comptage des jeux
    .groupBy("price_bin", "price_status")
    .agg(
        F.count("*").alias("game_nb")
    )

    .orderBy("price_bin")
)

display(result)

price_bin,price_status,game_nb
0,Prix courant,467835
5,Prix courant,226473
10,Prix courant,113600
15,Prix courant,81158
20,Prix courant,20153
25,Outlier statistique,17354
25,Prix courant,159
30,Outlier statistique,3004
35,Outlier statistique,8054
40,Outlier statistique,946


In [0]:
clean_df.printSchema()

root
 |-- developer: string (nullable = true)
 |-- name: string (nullable = true)
 |-- owners: string (nullable = true)
 |-- publisher: string (nullable = true)
 |-- short_description: string (nullable = true)
 |-- category: string (nullable = false)
 |-- language: string (nullable = false)
 |-- extracted_genre: string (nullable = false)
 |-- extracted_tag: string (nullable = false)
 |-- extracted_platform: string (nullable = false)
 |-- appid: integer (nullable = true)
 |-- ccu: integer (nullable = true)
 |-- discount: short (nullable = true)
 |-- initialprice: decimal(5,2) (nullable = true)
 |-- negative: integer (nullable = true)
 |-- positive: integer (nullable = true)
 |-- price: decimal(5,2) (nullable = true)
 |-- release_date: date (nullable = true)
 |-- required_age: short (nullable = true)
 |-- extracted_owners: integer (nullable = true)
 |-- tag_vote_nb: integer (nullable = true)



In [0]:
from pyspark.sql import functions as F

bin_width = 5

price_owners = (clean_df
    # 1. Transformation de owners :
    # "20,000 .. 50,000" -> min = 20000 / max = 50000
    .withColumn('owners_min', regexp_replace(split(col('owners'), ' ')[0], ',', '').cast("int")) # keep only low owners number
    .withColumnRenamed('extracted_owners', 'owners_max')
    # 3. Création des tranches de prix
    # 0-5$, 5-10$, 10-15$...
    .withColumn("price_bin",
        F.floor(F.col("price") / bin_width) * bin_width)
    # 4. Agrégation par tranche de prix
    .dropDuplicates(['appid'])
    .groupBy("price_bin")
    .agg(
        F.count("appid").alias("game_nb"),
        F.sum("owners_max").alias("total_owners"),
        F.avg("owners_max").alias("mean_owners"))
    # 5. Coefficient :
    # nombre moyen d'owners par jeu dans la tranche
    .withColumn(
        "coef",
        F.col("total_owners") / F.col("game_nb") * 0.0001)
    .orderBy("price_bin")
)

display(price_owners)

price_bin,game_nb,total_owners,mean_owners,coef
0,31162,4955860000,159035.36358385213,15.903536358385214
5,12428,1477360000,118873.51142581269,11.887351142581268
10,5302,865270000,163196.90682761223,16.319690682761223
15,3705,1463920000,395120.1079622132,39.512010796221325
20,910,244020000,268153.8461538461,26.815384615384612
25,882,536700000,608503.4013605443,60.85034013605443
30,162,67500000,416666.6666666667,41.66666666666667
35,438,389540000,889360.7305936073,88.93607305936074
40,47,46140000,981702.1276595745,98.17021276595746
45,192,83640000,435625.0,43.5625


In [0]:
from pyspark.sql import functions as F

bin_width = 5

price_owners = (
    clean_df
    .withColumnRenamed('extracted_owners', 'owners_max')
    # 3. Création des tranches de prix
    .withColumn(
        "price_bin",
        F.floor(F.col("price") / bin_width) * bin_width
    )

    # 4. Agrégation par tranche de prix
    .groupBy("price_bin")
    .agg(
        F.countDistinct("appid").alias("game_nb"),
        F.sum("owners_max").alias("total_owners"),
        F.avg("owners_max").alias("mean_owners")
    )

    # 5. Coefficient logarithmique
    .withColumn(
        "coef_log",
        F.log10(F.col("mean_owners") + 1)
    )

    .orderBy("price_bin")
)

display(price_owners)

price_bin,game_nb,total_owners,mean_owners,coef_log
0,31162,149624690000,319823.63440101745,5.5049119121068655
5,12428,53297360000,235336.48602703193,5.371691109828089
10,5302,30663750000,269927.3767605634,5.431248543032687
15,3705,43671040000,538099.0167327928,5.730863005551344
20,910,8673990000,430406.8873120627,5.633880221265954
25,882,15688840000,895839.6619653972,5.952230771065149
30,162,2694330000,896914.1145139814,5.952751342662139
35,438,10826680000,1344261.236652595,6.128483998496013
40,47,1258260000,1330084.5665961944,6.123879580745446
45,192,2034570000,690621.1812627291,5.839240522819264


In [0]:
# création d'un coefficient issu du rapport nb_games / nb_owners
# Select first periods of time series data based on a date offset.
'''game_nb = result.select("game_nb").first()["game_nb"]
mean_owners = clean_df.select("mean_owners").first()["mean_owners"]

coef_df = spark.createDataFrame(
    [(game_nb, mean_owners, game_nb / mean_owners)],
    ["game_nb", "mean_owners", "coef"]
)

display(coef_df)'''

'game_nb = result.select("game_nb").first()["game_nb"]\nmean_owners = clean_df.select("mean_owners").first()["mean_owners"]\n\ncoef_df = spark.createDataFrame(\n    [(game_nb, mean_owners, game_nb / mean_owners)],\n    ["game_nb", "mean_owners", "coef"]\n)\n\ndisplay(coef_df)'

In [0]:
outlier_games = (
    price_df
    .filter(F.col("price") > upper_bound)
    .select('appid', "name", "price")
    .distinct()
    .orderBy(F.desc("price"))
)

display(outlier_games)

appid,name,price
1200520,ascent free-roaming vr experience,999.00
253670,aartform curvy 3d 3.0,299.90
502570,houdini indie,269.99
2070990,vegas edit 20 steam edition,249.00
1538090,virtual orator,199.99
1289890,vr long march,199.99
951030,derelict (do not buy),199.99
1720060,earthquake escape,199.99
438450,3df zephyr lite steam edition,199.99
1035340,眼睛（眼球）结构研究,199.99


Prices varies on a scale from 0 to 999 $, sometime of any cents. Mean price is 7,73 $ with an initial price higher on 7,93 $ (cf last run clean_df.describe() command). 

In [0]:
result = clean_df \
    .select('appid', 'price') \
    .distinct() \
    .groupBy(
        (F.floor(F.col('price') / 10)).alias('range_price')) \
    .agg(F.count('price').alias('game_nb')) \
    .orderBy('range_price')
display(result)

range_price,game_nb
0,43590
1,9007
2,1792
3,600
4,239
5,206
6,34
7,16
8,6
9,29


Databricks visualization. Run in Databricks to view.

#### Prices don't change ? 

In [0]:
result = clean_df \
    .select('appid', 'price', 'initialprice', 'discount') \
    .distinct() \
    .filter((clean_df['price'] != clean_df['initialprice']) & (clean_df['discount'] == 0))
result.show()

+-----+-----+------------+--------+
|appid|price|initialprice|discount|
+-----+-----+------------+--------+
+-----+-----+------------+--------+



We compared price and initialprice on nodiscount products. There is no result, so prices change only with discount.

#### Are there many games with a discount?

Prices varies relying to discount. Le discount varie de 0 à 90 avec une valeur moyenne de 2,6. Le discount est rare.

In [0]:
discount_nb = clean_df \
    .select(clean_df['appid'], 'price', 'initialprice', 'discount') \
    .filter(clean_df.discount > 0) \
    .distinct() \
    .agg(count('discount').alias('discount_nb'))

discount_nb = discount_nb.collect()[0][0]

games_total = games_nb

discount_pct = discount_nb / games_total * 100

print(f'discount_nb = {discount_nb} \
    \ngames_total = {games_nb} \
    \ndiscount_pct = {discount_pct}')


discount_nb = 2515     
games_total = 55556     
discount_pct = 4.526963784289725


2515 games on discount represents only 4,53% of games.

In [0]:
from pyspark.sql.functions import count, desc, floor, col, concat, lit

result = clean_df \
    .select('appid', 'discount') \
    .filter(clean_df.discount != 0 ) \
    .withColumn('discount_bracket', (floor(col('discount') / 10) * 10)) \
    .distinct() \
    .groupBy('discount_bracket') \
    .agg(count('*').alias('game_nb')) \
    .orderBy(desc('discount_bracket'))
    
result.display()

discount_bracket,nb_games
90,239
80,377
70,409
60,236
50,526
40,220
30,196
20,209
10,103


In [0]:
from pyspark.sql.functions import count, desc, floor, col, concat, lit

result = clean_df \
    .select('discount', 'appid', 'publisher') \
    .distinct() \
    .filter(clean_df.discount != 0 ) \
    .groupBy('discount', 'publisher') \
    .agg(count('discount').alias('game_nb')) \
    .orderBy(desc('game_nb')) \
    .limit(5)
    
result.display()

discount,publisher,nb_games
80,strategy first,38
90,8floor,28
75,funbox media ltd,22
70,andy jurko,17
48,sometimes you,15


In [0]:
result = clean_df \
    .select('appid', 'publisher', 'discount') \
    .filter( \
        (clean_df.discount != 0) \
        & (clean_df.publisher.isin(['big fish games', 'ubisoft','valve']))) \
    .distinct() \
    .groupBy('publisher') \
    .agg(count('*').alias('game_nb'))
    
result.display()

publisher,nb_games
ubisoft,7


Notre société Ubisoft propose 7 références en discount.

In [0]:
# to DO - graph pour montrer la relation discount / nb acheteurs
result = clean_df \
    .select(clean_df['appid'], 'discount', 'owners') \
    .filter(clean_df.discount != 0 ) \
    .distinct() \
    .groupBy('owners') \
    .agg(count('discount').alias('game_nb')) \
    .orderBy(desc('game_nb'))

result.display()

owners,games_nb
"0 .. 20,000",1516
"20,000 .. 50,000",366
"50,000 .. 100,000",232
"100,000 .. 200,000",162
"200,000 .. 500,000",144
"500,000 .. 1,000,000",45
"1,000,000 .. 2,000,000",28
"2,000,000 .. 5,000,000",16
"5,000,000 .. 10,000,000",4
"50,000,000 .. 100,000,000",1


In [0]:
# TO DO Nico - graph pour suivre l'évolution du discount

result = clean_df \
    .select(clean_df['release_date'], 'appid', 'discount') \
    .filter(clean_df.discount != 0 ) \
    .withColumn('release_year', year(to_date(col('release_date')))) \
    .distinct() \
    .groupBy('release_year') \
    .agg(count('*').alias('game_nb')) \
    .orderBy(desc('game_nb'))

result.display()

release_year,games_nb
2022,513
2021,453
2020,325
2018,292
2019,291
2017,198
2016,171
2015,108
2014,83
2013,25


Est-ce que ces jeux discount restent proposés en vente ?

In [0]:
result = clean_df \
    .select('extracted_genre', 'discount') \
    .filter(clean_df.discount != 0 ) \
    .distinct() \
    .groupBy('extracted_genre') \
    .agg(count('discount').alias('game_nb')) \
    .orderBy(desc('game_nb'))

result.display()

extracted_genre,games_nb
action,54
adventure,45
casual,39
indie,29
simulation,16
strategy,12
racing,12
rpg,12
audio production,4
design & illustration,4


### languages

What are the most represented languages?

In [0]:
from pyspark.sql.functions import col, explode, split, trim
result = clean_df \
    .select('appid', "language", 'name') \
    .groupBy("language") \
    .agg(countDistinct("appid").alias("game_nb")) \
    .orderBy("game_nb", ascending=False)

result.display(truncate=False)

language,game_nb
english,54520
simplified chinese,569
japanese,197
russian,84
traditional chinese,44
korean,24
german,23
french,20
czech,12
portuguese - brazil,11


In 2022, the most supported language is english with 54768 games, then german and chineese. French on 4th row with 13414 games before russian.

Are there many games prohibited for children under 16/18 ?

In [0]:
result = clean_df \
    .select('required_age') \
    .filter(clean_df['required_age'].between(16, 21)) \
    .groupBy("required_age") \
    .agg(count("*").alias("forbidden_games_nb")) \
    .orderBy('required_age')
result.display()

required_age,forbidden_games_nb
16,703
17,776
18,4307
20,11
21,15


Ca représente quel pourcentage ?

In [0]:
result = clean_df \
    .select('name', 'required_age', 'genre', 'languages', 'tag') \
    .filter(clean_df['required_age'].between(16, 21)) \
    .orderBy('required_age')
result.display()

### tags

Quels sont les tags les plus représentés sur les jeux interdits aux mineurs ?

In [0]:
result = clean_df \
    .select('appid', 'required_age', 'extracted_tag', 'name') \
    .filter(clean_df['required_age'].between(16, 21)) \
    .dropDuplicates(['appid']) \
    .groupBy("extracted_tag") \
    .agg(count("extracted_tag").alias("game_nb")) \
    .orderBy('game_nb', ascending=False)
result.display()

extracted_tag,game_nb
action,146
adventure,37
3d,28
2d,24
anime,18
2.5d,6
indie,6
casual,4
atmospheric,4
1990's,4


# Genre analysis

#### What are the most represented genres?

In [0]:
top_genre = clean_df \
    .select('appid', 'extracted_genre') \
    .dropDuplicates(['appid', 'extracted_genre']) \
    .groupBy('extracted_genre') \
    .agg(countDistinct('appid').alias('games_nb')) \
    .orderBy(desc('games_nb')) \
    .limit(5)

top_genre.show()

+---------------+--------+
|extracted_genre|games_nb|
+---------------+--------+
|         action|   23564|
|      adventure|   11254|
|         casual|    9726|
|          indie|    5400|
|     simulation|    1206|
+---------------+--------+



In 2022, the trend genre is : 
- 1st indie with 39681 games, 
- 2d action with 23759 games, 
- 3d casual with 22086 games. Warning : multiple genres coexist on games.

#### Are there any genres that have a better positive/negative review ratio?

In [0]:
reviewed_ratio = clean_df \
    .select('appid', 'extracted_genre', 'positive', 'negative') \
    .dropDuplicates(['appid', 'extracted_genre']) \
    .groupBy('extracted_genre') \
    .agg(F.sum('positive').alias('positive_sum'), F.sum('negative').alias('negative_sum')) \
    .withColumn('ratio', col('positive_sum') /  col('negative_sum')) \
    .orderBy(desc('ratio')) \
    .limit(5)
reviewed_ratio.show(truncate=False)    

Genres with the best review ratio are :
- 1 photo editing with 42 positive advices for 1 negative
- 2 animation & modeling with 26 positive advices for 1 negative
- 3 design & illustration with 25 positive advices for 1 negative

#### Do some publishers have favorite genres?

In [0]:
top_publishers = clean_df \
    .select('appid', 'publisher', 'extracted_genre') \
    .dropDuplicates(['appid', 'extracted_genre']) \
    .groupBy('publisher', 'extracted_genre') \
    .agg(count('extracted_genre').alias('games_nb')) \
    .orderBy(desc('games_nb'))
top_publishers.show(truncate=False)

In [0]:
from pyspark.sql.functions import count

pivot_publishers_strategy = clean_df \
    .dropDuplicates(['appid', 'extracted_genre']) \
    .filter(clean_df.publisher.isin('big fish games', '8floor', 'choice of games', 'hh-games', 'laush studio', 'valve', 'ubisoft')) \
    .groupBy('extracted_genre') \
    .pivot('publisher') \
    .agg(count('appid').alias('games_nb')) \
    .na.fill(0)
pivot_publishers_strategy.display()

In [0]:
pivot_pd = pivot_publishers_strategy.toPandas().set_index('extracted_genre')
pivot_pct = pivot_pd.div(pivot_pd.sum(axis=0), axis=1) * 100
pivot_pct = pivot_pct.round(2)
(display(pivot_pct.reset_index())) # avoid loose label genres

Factually, offer is oriented. Leaders companies label more than 50% of their products on one or two genres, mostly beetween casual, adventure, indie, strategy. Some companies sont plus diversifiées et misent sur une niche strategy sur du rpg et de l'action.   
- 1 big fish games target casual and adventure (50% / 47%)
- 2 8floor target casual at 75%
- 3 choice of games est spécialisé en rpg. Il est également présent sur le indie et adventure (32% / 32% / 26%)
- 4 hh-games cible casual, indie, action et adventure (39% to 11%)
- 5 laush studio target indie and casual (45% / 32%)
- outsider valve target action at 60%
- Ubisoft action at (32% / 30% )

#### What are the most lucrative genres?

# Platform analysis

Are most games available on Windows/Mac/Linux instead?

In [0]:
from pyspark.sql.functions import count

top_platform = clean_df \
    .select('appid', 'extracted_platform') \
    .distinct() \
    .groupBy('extracted_platform') \
    .agg(count("extracted_platform").alias("games_nb")) \
    .orderBy('games_nb', ascending=False)
top_platform.show(truncate=False)

In [0]:
platform_pd = top_platform.toPandas().set_index('extracted_platform')
pct_platform = platform_pd.div(platform_pd.sum(axis=0), axis=1) * 100
pct_platform = pct_platform.round(2)
(display(pct_platform.reset_index())) # avoid loose label

Nous avons déjà les résultats :
windows is leader (74%), linux and mac share the rest. Bien que linux soit plus récent que mac, son écosystem libre semble plus adapté que mac. 
- 1 windows with 41164 supported games
- 2 linux (8435)
- 3 mac (5957)

Are any games developped specifically on a platform ?

In [0]:
mono_id = clean_df \
    .select('appid', 'extracted_platform') \
    .distinct() \
    .groupBy('appid') \
    .agg(F.count('appid').alias('platform_nb')) \
    .filter(F.col('platform_nb') == 1) \
    .orderBy(F.desc('platform_nb')) \
        
mono_platform = clean_df.select('appid', 'extracted_platform').distinct() \
    .join(mono_id.select('appid'), on='appid', how='inner')
mono_platform.show()

+------------------+-----------+
|extracted_platform|platform_nb|
+------------------+-----------+
+------------------+-----------+



Les jeux développés spécifiquement pour linux restent rares(3).

Evolution de la répartition des platform par date de release table pivot


Do certain genres tend to be preferentially available on certain platforms?

In [0]:
clean_df.printSchema()